// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWTSx30BLaN3PBQEI1GjZOvvETAN-ieE',
    appId: '1:487965946836:web:4f2eb65f73b0d58061dc41',
    messagingSenderId: '487965946836',
    projectId: 'pocket-expense-tracker-app',
    authDomain: 'pocket-expense-tracker-app.firebaseapp.com',
    storageBucket: 'pocket-expense-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrteHZQtO-jGdXPMd34MWgI5ZY9VNk_eQ',
    appId: '1:487965946836:android:84a04da994072a7461dc41',
    messagingSenderId: '487965946836',
    projectId: 'pocket-expense-tracker-app',
    storageBucket: 'pocket-expense-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2TMCAx03fb1ugwHFMJh15tX-vq9aEWNg',
    appId: '1:487965946836:ios:3bcb8a264b80827761dc41',
    messagingSenderId: '487965946836',
    projectId: 'pocket-expense-tracker-app',
    storageBucket: 'pocket-expense-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.pocketExpenseTrackerApp',
  );
}
